import 'package:flutter/material.dart';
import 'package:doubanMovie/api/DioManger.dart';
import 'package:doubanMovie/api/JKApi.dart';
import 'package:doubanMovie/api/JKMethod.dart';
import 'package:doubanMovie/Model.dart';
import 'package:doubanMovie/views/HomeItemView.dart';
class Home extends StatelessWidget {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("首页"),
        ),
        body: Center(
          child: MoiveList(),
          ),
      
    );
  }
}

class MoiveList extends StatefulWidget {
  MoiveList({Key key}) : super(key: key);

  @override
  _MoiveListState createState() => _MoiveListState();
}

class _MoiveListState extends State<MoiveList> {
  List<Subjects> list = [];
  int count;
  int start;

  

  @override
  void initState() {
    super.initState();
    getList();
  }

  void getList(){
        DioManager().requestList(JKMethod.GET, 
    JKApi.top250,
    params: {"count":10,"start":0},
    success: (data){
        // print("success data = $data");
       Autogenerated C =  Autogenerated.fromJson(data);
       setState(() {
         list.addAll(C.subjects);
       });
      
    },
    error: (error){
       print("error code = ${error.code}, massage = ${error.message}");
    }
    );
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: list?.length??0,
      itemBuilder:(BuildContext context,int index){
        return HomeItemView(model: list[index],rank: index+1,);
      },
      
    );
  }
}