class Autogenerated {
  int count;
  int start;
  List<Subjects> subjects;
  int total;

  Autogenerated({this.count, this.start, this.subjects, this.total});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    count = json['count'];
    start = json['start'];
    if (json['subjects'] != null) {
      subjects = new List<Subjects>();
      json['subjects'].forEach((v) {
        subjects.add(new Subjects.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    data['start'] = this.start;
    if (this.subjects != null) {
      data['subjects'] = this.subjects.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class Subjects {
  List<Casts> casts;
  int commentsCount;
  List<String> countries;
  List<Directors> directors;
  List<String> genres;
  int id;
  Avatars images;
  String originalTitle;
  Rating rating;
  int reviewsCount;
  String summary;
  String title;
  String warning;
  int wishCount;
  int year;

  Subjects(
      {this.casts,
      this.commentsCount,
      this.countries,
      this.directors,
      this.genres,
      this.id,
      this.images,
      this.originalTitle,
      this.rating,
      this.reviewsCount,
      this.summary,
      this.title,
      this.warning,
      this.wishCount,
      this.year});

  Subjects.fromJson(Map<String, dynamic> json) {
    if (json['casts'] != null) {
      casts = new List<Casts>();
      json['casts'].forEach((v) {
        casts.add(new Casts.fromJson(v));
      });
    }
    commentsCount = json['comments_count'];
    countries = json['countries'].cast<String>();
    if (json['directors'] != null) {
      directors = new List<Directors>();
      json['directors'].forEach((v) {
        directors.add(new Directors.fromJson(v));
      });
    }
    genres = json['genres'].cast<String>();
    id = json['id'];
    images =
        json['images'] != null ? new Avatars.fromJson(json['images']) : null;
    originalTitle = json['original_title'];
    rating =
        json['rating'] != null ? new Rating.fromJson(json['rating']) : null;
    reviewsCount = json['reviews_count'];
    summary = json['summary'];
    title = json['title'];
    warning = json['warning'];
    wishCount = json['wish_count'];
    year = json['year'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.casts != null) {
      data['casts'] = this.casts.map((v) => v.toJson()).toList();
    }
    data['comments_count'] = this.commentsCount;
    data['countries'] = this.countries;
    if (this.directors != null) {
      data['directors'] = this.directors.map((v) => v.toJson()).toList();
    }
    data['genres'] = this.genres;
    data['id'] = this.id;
    if (this.images != null) {
      data['images'] = this.images.toJson();
    }
    data['original_title'] = this.originalTitle;
    if (this.rating != null) {
      data['rating'] = this.rating.toJson();
    }
    data['reviews_count'] = this.reviewsCount;
    data['summary'] = this.summary;
    data['title'] = this.title;
    data['warning'] = this.warning;
    data['wish_count'] = this.wishCount;
    data['year'] = this.year;
    return data;
  }
}

class Casts {
  Avatars avatars;
  String name;

  Casts({this.avatars, this.name});

  Casts.fromJson(Map<String, dynamic> json) {
    avatars =
        json['avatars'] != null ? new Avatars.fromJson(json['avatars']) : null;
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.avatars != null) {
      data['avatars'] = this.avatars.toJson();
    }
    data['name'] = this.name;
    return data;
  }
}

class Directors {
  Avatars avatars;
  String name;

  Directors({this.avatars, this.name});

  Directors.fromJson(Map<String, dynamic> json) {
    avatars =
        json['avatars'] != null ? new Avatars.fromJson(json['avatars']) : null;
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.avatars != null) {
      data['avatars'] = this.avatars.toJson();
    }
    data['name'] = this.name;
    return data;
  }
}
class Avatars {
  String large;

  Avatars({this.large});

  Avatars.fromJson(Map<String, dynamic> json) {
    large = json['large'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['large'] = this.large;
    return data;
  }
}


class Rating {
  double average;
  int max;
  int min;
  String stars;

  Rating({this.average, this.max, this.min, this.stars});

  Rating.fromJson(Map<String, dynamic> json) {
    average = json['average'];
    max = json['max'];
    min = json['min'];
    stars = json['stars'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['average'] = this.average;
    data['max'] = this.max;
    data['min'] = this.min;
    data['stars'] = this.stars;
    return data;
  }
}
